services:
  demo:
    build: .
    image: zakuro/zakuro-cache
    command: time python demo.py

  demo-nocache:
    build: .
    image: zakuro/zakuro-cache
    command: time python demo.py --nocache

  test:
    build: .
    image: zakuro/zakuro-cache
    command: python -m pytest tests/ -v
